### ISSUE TITLE
Cant get WithActivationStrategy to work with grain in cluster.

### ISSUE THREAD

**Issue by Donk3ys** [Tochemey/goakt#973]
First of all thanks for this package.

I'm trying to test grain activation using `WithActivationStrategy`. I've tried all the different types and had no success.

I have 2 nodes: `node1` and `node2`.
Maybe I'm not understanding correctly but I'm trying to use `node1(leader)` to get grain identity for all the grains using `RoundRobinActivation` and I'm expecting them to be activated on `node1` then `node2` then back to `node1` etc.

What I'm seeing is all grains are being activated only on `node1`.
When I check  `actorSystem.InCluster()` both return true.

[Here](https://github.com/Donk3ys/goakt-cluster) is my example code.

**Comment by Tochemey** [comment]
@Donk3ys Thanks for reporting the issue. I will take a look and get back to you.

**Comment by Tochemey** [comment]
In the meantime @Donk3ys did you take a look at this https://github.com/Tochemey/goakt-examples/tree/main/grains-cluster/grains-dnssd?

**Comment by Donk3ys** [comment]
> In the meantime @Donk3ys did you take a look at this https://github.com/Tochemey/goakt-examples/tree/main/grains-cluster/grains-dnssd?

I had a look but didn't spin it up on my machine. I'll give it a try  and report back.

**Comment by Tochemey** [comment]
@Donk3ys I am looking into your issue now

**Comment by Tochemey** [comment]
@Donk3ys I have seen an issue with the round-robin strategy. I will provide a fix and push.

**Comment by Donk3ys** [comment]
> @Donk3ys I have seen an issue with the round-robin strategy. I will provide a fix and push.

Amazing, thanks so much for the quick response.

I'm not sure if you checked the other strategies as Random and LeastLoad had the same issue for me.

**Comment by Tochemey** [comment]
@Donk3ys Random pick any node at random. We cannot really control that. Regarding the LeastLoad I will check if there is bug

**Comment by Tochemey** [comment]
@Donk3ys I’ve pushed the fix. You can verify it using this [commit](https://github.com/Tochemey/goakt/pull/974/commits/cb9de9e2744057c5b17887ecbb8329e8bb43a35b). The previous implementation contained some inaccuracies.

**Comment by Tochemey** [comment]
Once again thanks for reporting this bug

**Comment by Donk3ys** [comment]
> [@Donk3ys](https://github.com/Donk3ys) I’ve pushed the fix. You can verify it using this [commit](https://github.com/Tochemey/goakt/pull/974/commits/cb9de9e2744057c5b17887ecbb8329e8bb43a35b). The previous implementation contained some inaccuracies.

Thank you.
I've tested, `RoundRobin` works great,  as well as `Random` are working as expected.

I did update my [example](https://github.com/Donk3ys/goakt-cluster) to test `LeastLoadActivation` by adding Fibonacci function to run on the node activating all the grains.

Even when the node gets to 90% and the other node is at 0% cpu the grains are still getting activated on the 'busy' node and no grains are activated on the 'idle' node

Maybe something to check also.

**Comment by Tochemey** [comment]
@Donk3ys By the way you don't need to do this https://github.com/Donk3ys/goakt-cluster/blob/master/cmd/main.go#L77 to activate grains. GoAkt really does not care about leader node unless there is a cluster topology change and actors or grains need to be relocated. Moreover the latest commit should be ok.

**Comment by Donk3ys** [comment]
> [@Donk3ys](https://github.com/Donk3ys) By the way you don't need to do this https://github.com/Donk3ys/goakt-cluster/blob/master/cmd/main.go#L77 to activate grains. GoAkt really does not care about leader node unless there is a cluster topology change and actors or grains need to be relocated. Moreover the latest commit should be ok.

Yeah, I was just using this to force 1 node to create all the actors for my testing

**Comment by Tochemey** [comment]
@Donk3ys I will cut a new release tag in a couple of days. Thanks for reporting the bug. By the way from your sample app I can imagine you may be interested in event sourcing/cqrs. If that the case you can check this repo out: https://github.com/Tochemey/ego. Unfortunately it does not rely on Grains because it was created before I added Grains and I need proper planning to migrate it to use Grains.

**Comment by Tochemey** [comment]
@Donk3ys New release tag is out https://github.com/Tochemey/goakt/releases/tag/v3.9.8. Thanks for the reported issue. In case you have any feedback while using the framework please let us know either via the `discussions`
